[build]
builder = "dockerfile"
dockerfilePath = "AsistanApp/Dockerfile"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
healthcheckPath = "/health/live"
healthcheckTimeout = 60
